server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AkulaApoorva/olx-config.git
          default-label: main
          username: AkulaApoorva
          clone-on-start: true
